//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("OgcToolkit.WebSample.Models.ModelFirst", "FK_Record_Relation", "Records", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(OgcToolkit.WebSample.Models.ModelFirst.MFRecord), "Records1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OgcToolkit.WebSample.Models.ModelFirst.MFRecord), true)]

#endregion

namespace OgcToolkit.WebSample.Models.ModelFirst
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MFConceptualEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MFConceptualEntities object using the connection string found in the 'MFConceptualEntities' section of the application configuration file.
        /// </summary>
        public MFConceptualEntities() : base("name=MFConceptualEntities", "MFConceptualEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MFConceptualEntities object.
        /// </summary>
        public MFConceptualEntities(string connectionString) : base(connectionString, "MFConceptualEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MFConceptualEntities object.
        /// </summary>
        public MFConceptualEntities(EntityConnection connection) : base(connection, "MFConceptualEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MFRecord> MFRecords
        {
            get
            {
                if ((_MFRecords == null))
                {
                    _MFRecords = base.CreateObjectSet<MFRecord>("MFRecords");
                }
                return _MFRecords;
            }
        }
        private ObjectSet<MFRecord> _MFRecords;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MFRecords EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMFRecords(MFRecord mFRecord)
        {
            base.AddObject("MFRecords", mFRecord);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OgcToolkit.WebSample.Models.ModelFirst", Name="MFRecord")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MFRecord : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MFRecord object.
        /// </summary>
        /// <param name="identifier">Initial value of the Identifier property.</param>
        /// <param name="subject">Initial value of the Subject property.</param>
        public static MFRecord CreateMFRecord(global::System.String identifier, MFRecordSubject subject)
        {
            MFRecord mFRecord = new MFRecord();
            mFRecord.Identifier = identifier;
            mFRecord.Subject = StructuralObject.VerifyComplexObjectIsNotNull(subject, "Subject");
            return mFRecord;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Identifier
        {
            get
            {
                return _Identifier;
            }
            set
            {
                if (_Identifier != value)
                {
                    OnIdentifierChanging(value);
                    ReportPropertyChanging("Identifier");
                    _Identifier = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Identifier");
                    OnIdentifierChanged();
                }
            }
        }
        private global::System.String _Identifier;
        partial void OnIdentifierChanging(global::System.String value);
        partial void OnIdentifierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.String _Date;
        partial void OnDateChanging(global::System.String value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Format
        {
            get
            {
                return _Format;
            }
            set
            {
                OnFormatChanging(value);
                ReportPropertyChanging("Format");
                _Format = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Format");
                OnFormatChanged();
            }
        }
        private global::System.String _Format;
        partial void OnFormatChanging(global::System.String value);
        partial void OnFormatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Relation
        {
            get
            {
                return _Relation;
            }
            set
            {
                OnRelationChanging(value);
                ReportPropertyChanging("Relation");
                _Relation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Relation");
                OnRelationChanged();
            }
        }
        private global::System.String _Relation;
        partial void OnRelationChanging(global::System.String value);
        partial void OnRelationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Spatial
        {
            get
            {
                return _Spatial;
            }
            set
            {
                OnSpatialChanging(value);
                ReportPropertyChanging("Spatial");
                _Spatial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Spatial");
                OnSpatialChanged();
            }
        }
        private global::System.String _Spatial;
        partial void OnSpatialChanging(global::System.String value);
        partial void OnSpatialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Coverage
        {
            get
            {
                return StructuralObject.GetValidValue(_Coverage);
            }
            set
            {
                OnCoverageChanging(value);
                ReportPropertyChanging("Coverage");
                _Coverage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Coverage");
                OnCoverageChanged();
            }
        }
        private global::System.Byte[] _Coverage;
        partial void OnCoverageChanging(global::System.Byte[] value);
        partial void OnCoverageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AnyText
        {
            get
            {
                return _AnyText;
            }
            set
            {
                OnAnyTextChanging(value);
                ReportPropertyChanging("AnyText");
                _AnyText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AnyText");
                OnAnyTextChanged();
            }
        }
        private global::System.String _AnyText;
        partial void OnAnyTextChanging(global::System.String value);
        partial void OnAnyTextChanged();

        #endregion
        #region Complex Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmComplexPropertyAttribute()]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
        [XmlElement(IsNullable=true)]
        [SoapElement(IsNullable=true)]
        [DataMemberAttribute()]
        public MFRecordSubject Subject
        {
            get
            {
                _Subject = GetValidValue(_Subject, "Subject", false, _SubjectInitialized);
                _SubjectInitialized = true;
                return _Subject;
            }
            set
            {
                OnSubjectChanging(value);
                ReportPropertyChanging("Subject");
                _Subject = SetValidValue(_Subject, value, "Subject");
                _SubjectInitialized = true;
                ReportPropertyChanged("Subject");
                OnSubjectChanged();
            }
        }
        private MFRecordSubject _Subject;
        private bool _SubjectInitialized;
        partial void OnSubjectChanging(MFRecordSubject value);
        partial void OnSubjectChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OgcToolkit.WebSample.Models.ModelFirst", "FK_Record_Relation", "Records1")]
        public EntityCollection<MFRecord> Records1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MFRecord>("OgcToolkit.WebSample.Models.ModelFirst.FK_Record_Relation", "Records1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MFRecord>("OgcToolkit.WebSample.Models.ModelFirst.FK_Record_Relation", "Records1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OgcToolkit.WebSample.Models.ModelFirst", "FK_Record_Relation", "Records")]
        public MFRecord Records2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MFRecord>("OgcToolkit.WebSample.Models.ModelFirst.FK_Record_Relation", "Records").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MFRecord>("OgcToolkit.WebSample.Models.ModelFirst.FK_Record_Relation", "Records").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MFRecord> Records2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MFRecord>("OgcToolkit.WebSample.Models.ModelFirst.FK_Record_Relation", "Records");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MFRecord>("OgcToolkit.WebSample.Models.ModelFirst.FK_Record_Relation", "Records", value);
                }
            }
        }

        #endregion
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="OgcToolkit.WebSample.Models.ModelFirst", Name="MFRecordSubject")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class MFRecordSubject : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Subject
        {
            get
            {
                return _Subject;
            }
            set
            {
                OnSubjectChanging(value);
                ReportPropertyChanging("Subject");
                _Subject = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Subject");
                OnSubjectChanged();
            }
        }
        private global::System.String _Subject;
        partial void OnSubjectChanging(global::System.String value);
        partial void OnSubjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubjectScheme
        {
            get
            {
                return _SubjectScheme;
            }
            set
            {
                OnSubjectSchemeChanging(value);
                ReportPropertyChanging("SubjectScheme");
                _SubjectScheme = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SubjectScheme");
                OnSubjectSchemeChanged();
            }
        }
        private global::System.String _SubjectScheme;
        partial void OnSubjectSchemeChanging(global::System.String value);
        partial void OnSubjectSchemeChanged();

        #endregion
    }

    #endregion
    
}
