//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoSik.WebSample.Models.ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class MFRecord
    {
        public MFRecord()
        {
            this.Subject = new MFRecordSubject();
        }
    
        public string Identifier { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Date { get; set; }
        public string Type { get; set; }
        public string Format { get; set; }
        public string Relation { get; set; }
        public string Spatial { get; set; }
        public byte[] Coverage { get; set; }
        public string AnyText { get; set; }
    
        public MFRecordSubject Subject { get; set; }
    }
}
